# Generated by Django 3.1.7 on 2021-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0005_delete_place_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='lawyer_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('sublowers_allowed', models.IntegerField()),
            ],
        ),
    ]
