# Generated by Django 3.1.7 on 2021-03-18 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0006_lawyer_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('lisence_number', models.CharField(max_length=90)),
                ('bar_number', models.CharField(max_length=90)),
                ('is_approved', models.BooleanField(default=False)),
                ('selected_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.lawyer_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
