# Generated by Django 3.1.7 on 2021-03-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
